language: cpp
dist: bionic
os : linux

matrix:
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: COMPILER=g++-9
      
script:
    - g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DPACKAGE_TESTS=ON ..
    - cmake --build .
    - make test
  
  
