name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: format check
      shell: bash
      run: $GITHUB_WORKSPACE/clang-format-all.bsh $GITHUB_WORKSPACE

    - uses: EndBug/add-and-commit@v7 
      with:
        author_name: clang format