name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: format check
      shell: bash
      run: $GITHUB_WORKSPACE/clang-format-check.bsh $GITHUB_WORKSPACE