name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install clang-format
      shell: bash
      run: sudo apt install -y clang-format

    - name: help clang-format
      shell: bash
      run: clang-format --help

    - name: version clang-format
      shell: bash
      run: clang-format --version

    - name: format check
      shell: bash
      run: $GITHUB_WORKSPACE/clang-format-check.bsh $GITHUB_WORKSPACE