name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src ./test ./include'
        exclude: './test/extern'
        extensions: 'h,hpp,cpp,c'
        clangFormatVersion: 11
        inplace: True