name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: format check
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./.github/clang-format-check.bsh