name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: format check
      shell: bash
      run: ${{github.workspace}}/clang-format-check.bsh ${{github.workspace}}